libsel4vmmplatsupport/src/ioports.c

Previously, the 'end' of an IO port range was not inclusive. This would
result in a bug where one IO port whose value is the 'end' of a range
would be mistaken as being part of that range when it should not be.
This commit fixes it so that the 'end' of an IO port range is now
inclusive. Also harden the range overlap check.
This fixes this issue raised in http://sel4.systems/pipermail/devel/2020-March/002708.html.

libsel4vmmplatsupport: Fix an off-by-one error

---

libsel4vm/docs/libsel4vm_guest_memory.md
libsel4vm/include/sel4vm/guest_memory.h
libsel4vm/src/guest_memory.c
libsel4vm/src/guest_ram.c
libsel4vmmplatsupport/src/arch/x86/drivers/vmm_pci_helper.c
libsel4vmmplatsupport/src/arch/x86/guest_boot_init.c

These two commits fix #12. I'm not very familiar with this code base, I hope I'm not breaking more than I'm fixing here.
In particular this PR changes the prototype of `vm_reserve_anon_memory` to add a requested address alignment. For backward compatibility an alternative could be to add a new variant of this function, say `vm_reserve_anon_memory_aligned`, and have `vm_reserve_anon_memory` call `vm_reserve_anon_memory_aligned` with a requested alignment of one page. I'd happily do so if you think it's better.

Unaligned PCI BAR address fix

---

libsel4vm/src/arch/arm/vgic/vgic.h

gcc before version 10 silently merged these, from v10 on the linker fails with multiply defined symbols. We could pass `-fcommon` to get the old gcc behaviour, but it's better to fix the code.

vgic.h: global should be declared extern

---

.github/workflows/sel4test-sim.yml

ARMv6 is no longer supported.
See: seL4/seL4#578

.github: Remove ARMv6 tests

---

libsel4nanopb/src/common.c
libsel4rpc/src/client.c

- Add missing return statement
- Use correct protobuf stream types.
Signed-off-by: Kent McLeod <kent@kry10.com>

trivial: Fixup compiler warnings

---

libsel4vmmplatsupport/docs/libsel4vmmplatsupport_pci_helper.md
libsel4vmmplatsupport/docs/libsel4vmmplatsupport_virtio_net.md
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/pci_helper.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_net.h
libsel4vmmplatsupport/src/arch/arm/devices/vpci.c
libsel4vmmplatsupport/src/drivers/cross_vm_connection.c
libsel4vmmplatsupport/src/drivers/pci_helper.c
libsel4vmmplatsupport/src/drivers/virtio_con.c
libsel4vmmplatsupport/src/drivers/virtio_net.c

libsel4vmmplatsupport: fix PCI passthrough on ARM
BAR size resolution was emulated in two places, the fault handler and
the backend created with vmm_pci_create_passthrough_bar_emulation().
Move to vmm_pci_create_bar_emulation() on ARM as well and remove the
former. This way there is no need for BAR hack in the fault handler and
the backend created with vmm_pci_create_passthrough() works now on ARM.
Fix also several access size and bounds issues.
Signed-off-by: Hannu Lyytinen <hannux@ssrc.tii.ae>
Test with: seL4/camkes-vm#18

libsel4vmmplatsupport: fix PCI passthrough on ARM

---

libsel4vm/src/arch/arm/fault.c
libsel4vm/src/arch/arm/syscalls.c
libsel4vm/src/arch/arm/vm.c
libsel4vm/src/arch/x86/vm.c

This include file is deprecated since 2016, and it seems there's nothing in there that is needed. Removing the reference here is a preparation to delete this file from the kernel includes completely.
See https://github.com/axel-h/camkes-vm/pull/2 for CI tests.

libsel4vm: remove obsolete includes

---

libsel4vm/src/arch/arm/vgic/vgic.c

While the word "distributer" exists,  ARM uses "distributor".

[libsel4vm] trivial: use ARM terminology

---

libsel4vm/src/arch/arm/vgic/vgic.c

The real GIC has exactly zero or one pending request for any IRQ.
Signed-off-by: Hannu Lyytinen <hannux@ssrc.tii.ae>

libsel4vm: Enqueue IRQs only once

---

libsel4vm/src/arch/arm/vgic/vgic.c

The SPI related helper functions in `vgic.c` don't need `vcpu_id`, so I've removed them.
I find the `value` parameter to be ambiguous so I've tried to make it clearer.

trivial: cleanup helper functions setting VGIC distributor registers

---

libsel4vmmplatsupport/src/drivers/virtio_emul.c

Error: "vm_ram_touch@guest_ram.c:157 Failed to
touch ram region: Not registered RAM region".
Rootcause: if the value(unsigned int) is larger than 0x100000
(it is common when the memory of VM allocated exceeds 3G),
and then left shift 12 bit, the highest bits 0x1 of value will be lost.
Signed-off-by: hanjinglong <hjlallen@qq.com>

libsel4vmmplatsupport: fixed left shift overflow

---

libsel4vm/src/arch/arm/arm_vm.h
libsel4vm/src/arch/arm/vgic/vgic.c

For macos, expressions must be made atoms to avoid side effects.

add missing brackets

---

libsel4vmmplatsupport/CMakeLists.txt
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_blk.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_emul.h
libsel4vmmplatsupport/src/drivers/virtio_blk.c
libsel4vmmplatsupport/src/drivers/virtio_block_emul.c
libsel4vmmplatsupport/src/drivers/virtio_emul.c

This is what used to be https://github.com/seL4/seL4_projects_libs/pull/17
This commit combines a number of commits which do the following:
* Add virtio blk support to vmm
* Link satadrivers into vmm library so VMM can use virtio-blk
* Enable size max feature to virtio blk requests
* Refactor virtio blk code in libsel4vmm
* Cast values to avoid compiler warnings
CCDC-GVSC DISTRIBUTION A. Approved for public release; distribution
unlimited. OPSEC#4481.
Co-authored-by: Chris Guikema chris.guikema@dornerworks.com
Co-authored-by: Alex Pavey Alex.Pavey@Dornerworks.com
Signed-off-by: Damon Lee Damon.Lee@data61.csiro.au

Dornerworks sata

---

libsel4vm/src/arch/arm/vgic/vgic.c

libsel4vm: remove unused variables

---

libsel4vm/src/arch/arm/vgic/vgic.c

Another trivial code cleanup. 
At first I though this is something related to the misalignment fixed by https://github.com/seL4/seL4_projects_libs/pull/29 but it seems this just slipped in at e83bf5727db38f8ce899800d09555f930cad1217.

libsel4vm: use constant

---

libsel4vm/src/arch/arm/vgic/vgic.c

clean up log messages:
- fix line breaks in log messages
- use ZF_LOGx() instead of printf()

libsel4vm: fix line breaks in log messages

---

libsel4vm/src/arch/arm/vgic/vgic.c

These function always return success, so it makes the code simpler if we drop the return code.

libsel4vm: remove unused return values

---

libsel4vm/src/arch/arm/vgic/vgic.c

Reading `active0` to write `active_clr0` looks wrong somehow.

fix active_clr0 access 

---

libsel4vm/src/arch/arm/vgic/vgic.c

- Pass `vgic` to internal functions and not `vgic_dist_device` to reduce dependencies
- Pass dedicated parameters to the internal fault handlers.
The way I understand the code is, that `vgic` is the main object we work with internally. The `vgic_dist_device` seem something that describes the mapping. I'm not sure where this is really needed nowadays, maybe in a non-CAmkES environment there are usecases. But this is completely internal, so my longterm-goal is droping this completely and store the information in `vgic`, see top commit of https://github.com/Hensoldt-Cyber/seL4_projects_libs/commits/patch-axel-6a. I just have to check how well this works with the GICv3 support that https://github.com/seL4/seL4_projects_libs/pull/58 brings in.

Reduce dependency on vgic_dist_device

---

libsel4vmmplatsupport/src/arch/arm/guest_vcpu_util.c

This makes sure if generate_psci_node() returns an error other than FDT_ERR_EXISTS that it does not get ignored by
fdt_generate_plat_vcpu_node().

fdt_gen: Return error values correctly

---

libsel4vm/src/arch/arm/boot.c

This makes it easier to differentiate between the vcpu threads when debugging and/or testing

libsel4vm: change vcpu thread naming scheme

---

libsel4dma/src/dma.c
libsel4vm/src/arch/arm/vgic/gicv2.h
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/device_map.h
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/devices.h
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/guest_vcpu_util.h
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/vpci.h
libsel4vmmplatsupport/src/arch/arm/guest_image.c

I know its not a supported platform yet, but this should be able to be merged and it will be ready when the camkes-vm officially supports the board.

Add zynqmp support to libsel4vm

---

libsel4vmmplatsupport/CMakeLists.txt
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/device_map.h
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/devices.h
libsel4vmmplatsupport/plat_include/zynqmp/sel4vmmplatsupport/plat/vuart.h
libsel4vmmplatsupport/src/plat/zynqmp/devices/v_xuartps.c

This implementation has made several design decisions:
* No concept of an "active" uart
* The vuart TEMPTY interrupt status flag is kept asserted
* There is a predefined console
* Default serial port is UART0
The TEMPTY interrupt status flag is always asserted because it is set when writing the TX FIFO, but cleared when the interrupt is acknowledged. This causes a problem if a write to the TX FIFO occurs in the guest's interrupt handler, because the interrupt could be acknowledged after writing to the TX FIFO.
The vuart device immediately flushes all writes to the TX FIFO, so it is always empty. This commit will keep the TEMPTY flag set indefinitely to more closely emulate real hardware behavior.
Signed-off-by: Chris Guikema <chris.guikema@dornerworks.com>

libsel4vm: add vuart for zynqmp

---

libsel4vmmplatsupport/src/drivers/virtio_console_emul.c
libsel4vmmplatsupport/src/drivers/virtio_vsock_emul.c

This PR should fix a compilation error of multiple definitions (happens [here](https://github.com/seL4/camkes-vm/actions/runs/3562948885/jobs/5985186431)).
My version of Debian doesn't support gcc-10 so I can't test this locally. Let see how the CIs go.

trivial: fix compilation error

---

libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_console.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_emul.h
libsel4vmmplatsupport/src/drivers/virtio_console_emul.c
libsel4vmmplatsupport/src/drivers/virtio_emul.c
libsel4vmmplatsupport/src/drivers/virtio_net_emul.c

Fix the Copyright headers that have been altered incorrectly in a previous [PR](https://github.com/seL4/seL4_projects_libs/pull/74#issuecomment-1328653368).

trivial: revert Copyright headers

---

libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_con.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_console.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_vsock.h
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_vsock.h
libsel4vmmplatsupport/src/drivers/virtio_con.c
libsel4vmmplatsupport/src/drivers/virtio_console_emul.c
libsel4vmmplatsupport/src/drivers/virtio_vsock.c
libsel4vmmplatsupport/src/drivers/virtio_vsock_emul.c

- make emul_con_rx_complete deal with ring buffers to avoid an extra copy of the buffer from the virtio console backend to the emul layer. Previous discussion: https://github.com/seL4/camkes-vm/pull/36#discussion_r1019800073
- small refactor for virtio vsock and virtio console. Previous discussion: https://github.com/seL4/camkes-vm/pull/36#discussion_r1045428300
- depends on: https://github.com/seL4/camkes-vm/pull/36

virtio: improvement for virtio vsock and virtio console

---

libsel4vm/include/sel4vm/guest_vm.h
libsel4vmmplatsupport/src/arch/arm/guest_image.c

This commit adds three entries to the vm structure. The first is the entry address of the loaded kernel. The second is a flag to determine whether the cache should be cleaned when loading images to the guest's address space. The third flag is whether the VM should map memory 1:1.
These flags are necessary to differentiate VMs in a multiple VM setup. For example, if two VMs have kernels with different entry points, only one VM would run, and the other would fault.
Test with: https://github.com/seL4/camkes-vm-examples/pull/31
Test with: https://github.com/seL4/camkes-vm/pull/48

libsel4vm: add entries to vm structure

---

libsel4vmmplatsupport/src/arch/arm/guest_image.c

These functions seem purely internal, so there is no reason to expose them.

libsel4vmmplatsupport: make functions static

---

libsel4vmmplatsupport/src/arch/arm/guest_image.c

The last return statement is never reached.
Note that I think the `ram_base + 0x8000` might be wrong also and should also become  `vm->entry` now. But I will address this in a later PR then after more testing (https://github.com/Hensoldt-Cyber/seL4_projects_libs/commits/patch-axel-26a). It seems that zImage is no longer used for 64-bit anyway.

libsel4vmmplatsupport: remove superfluous statement

---

libsel4vmmplatsupport/src/ioports.c

Remove newline in the log messages, as `ZF_LOGx()` already prints a newline.

libsel4vmmplatsupport: remove newline

---

libsel4vm/docs/libsel4vm_guest_memory.md
libsel4vm/include/sel4vm/guest_memory.h
libsel4vm/src/guest_memory.c
libsel4vm/src/guest_ram.c
libsel4vmmplatsupport/src/drivers/cross_vm_connection.c
libsel4vmmplatsupport/src/guest_memory_util.c

The main reason for this change set is to support 2 MB and bigger CAmkES dataports. The tooling generates as large as possible frames for dataports, and for example on aarch64 the next step is 2 MB large page. However, the code deals only with 4 kB small pages. Let's use dataport's frame size instead of that default.

Cross-connector: use dataport frame size instead of 4k default

---

libsel4vmmplatsupport/src/ioports.c

Turn log level for io access to debug as this gets quite annoying when using the vm.

libsel4vmmplatsupport: reduce log level

---

libsel4vmmplatsupport/src/arch/arm/guest_image.c

Another follow-up from https://github.com/seL4/camkes-vm/pull/61 to remove explicit linux references

libsel4vmmplatsupport: remove more linux references

---

libsel4vm/src/arch/arm/vgic/virq.h

static_assert was standardized in C11 as a macro prior C23. While _Static_assert was introduced to C11 standard too, it's been part of GNU extensions and is available for GNU flavored standards prior C11.
Fixes compilation error on some versions of gcc.

libsel4vm: Adhere to gnu99 static assertion

---

libsel4vmmplatsupport/docs/libsel4vmmplatsupport_cross_vm_connection.md
libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/cross_vm_connection.h
libsel4vmmplatsupport/src/drivers/cross_vm_connection.c

Missing piece for #100 
Also fixes build problem introduced by seL4/camkes-vm#97

cross_vm_connectors: Derive size properly

---

libsel4vmmplatsupport/src/arch/arm/devices/vpci.c

The convenience function is moved to util_libs/libfdt, with naming and argument order changed to conform the style used in libfdt.
Test with: https://github.com/seL4/util_libs/pull/162

Remove duplicate code

---

libsel4vm/arch_include/x86/sel4vm/arch/guest_x86_context.h
libsel4vm/src/arch/x86/boot.c
libsel4vm/src/arch/x86/guest_state.h
libsel4vm/src/arch/x86/processor/decode.c

switch from `CONFIG_ARCH_X86_64` to `CONFIG_X86_64_VTX_64BIT_GUESTS` to allow 32 bit guests on 64 bit hosts.
This commit contains pieces that I omitted in the previous [code refactor](https://github.com/seL4/seL4_projects_libs/pull/16/commits/8227e006f50fbe981a1ce3791da5e11386c65bf5), and should be able to fix the [test failures](https://github.com/seL4/camkes-vm-examples/actions/runs/5273212619/jobs/9536500187).

64-bit-vms: small code refactoring

---

libsel4vm/CMakeLists.txt
libsel4vm/arch_include/arm/sel4vm/arch/guest_vm_arch.h
libsel4vm/src/arch/arm/boot.c
libsel4vm/src/arch/arm/vm.c
libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/smc.h
libsel4vmmplatsupport/src/arch/arm/psci.c
libsel4vmmplatsupport/src/arch/arm/psci.h
libsel4vmmplatsupport/src/arch/arm/smc.c
libsel4vmmplatsupport/src/arch/arm/smc.h
libsel4vmmplatsupport/src/sel4_arch/aarch64/smc.c

Add a new capability which certain threads can invoke so seL4 can make SMC calls on ARM platforms in EL2 (virtualized mode) on the thread’s behalf.
See https://sel4.atlassian.net/browse/RFC-9

SMC Capability

---

libsel4vm/src/arch/x86/processor/lapic.c

The subtraction is backwards, so lapic access will never work.

sel4vm, lapic: fix apic mmio access

---

libsel4vmmplatsupport/src/arch/x86/drivers/vmm_pci_helper.c

The offset is applied twice, which can prevent PCI passthrough from functioning properly when the offset is not zero. This commit removes the second offset addition.

vmmplatsupport, pci: fix offset bug

---

libsel4vmmplatsupport/src/arch/x86/guest_boot_init.c

This commit removes an e820 entry for 64-bit guests. This was a reserved memory region from the end of guest memory to the beginning of high memory. When 64-bit guests have access to 64-bit memory, this subtraction would place a bogus region in the e820 map that could confuse the guest.

vmmplatsupport, x86: remove e820 entry

---

libsel4vmmplatsupport/CMakeLists.txt
libsel4vmmplatsupport/src/arch/x86/guest_boot_init.c

The previous behavior would only attempt to map the vesa framebuffer and set the screen info struct if the vbe protection mode interface was successfully mapped in. This removes the dependency on the vbe protected mode interface. It is not clear that it is needed as vesa framebuffer passthrough works without it.

vmmplatsupport, vesa: fix vesa mapping

---

libsel4vm/src/arch/x86/processor/decode.c

This commit removes the newlines, as ZF_LOG adds a newline. It also fixes a DPRINTF level holdover, which causes a data fault when logging is enabled.

trivial, decode: fix zf_log statements

---

libsel4vmmplatsupport/CMakeLists.txt
libsel4vmmplatsupport/src/arch/x86/acpi.c

Real-time Linux kernels often don't work when using the PIT. This commit adds support for emulating the HPET.

vmmplatsupport: support hpet emulation

---

libsel4vm/src/arch/arm/vm.c

seL4_ARM_VCPU objects now allow single core configurations to access the VMPIDR register, thus this config guard is no longer needed.

libsel4vm: Remove SMP config guard on vmpidr reg

---

libsel4vm/src/arch/arm/syscalls.c

err = handle_syscall(vcpu);
If handle_syscall successfully processes, it will return VM_EXIT_HANDLED, which is defined as 1.
if (!err) {
The original condition !err is 0, causing the VM to block after successful processing.

vm_syscall_handler error

---

libsel4vm/src/guest_memory.c

Currently, if the `map_iterator` function fails to find a frame for a given address, then it breaks from the loop, but it does not return an error and marks the reservation as mapped. Since it skipped some number of reservations, that is not true and an error should be returned instead.

libsel4vm: Proper error for map_vm_memory_res

---

libsel4vmmplatsupport/src/drivers/cross_vm_connection.c
libsel4vmmplatsupport/src/plat/tk1/devices/usb.c
libsel4vmmplatsupport/src/plat/tk1/devices/vclock.c
libsel4vmmplatsupport/src/plat/tk1/devices/vuart.c

PAGE_SIZE_4K is a constant declared by one of our libraries, while PAGE_SIZE was previously provided by an older fork of the C library.

sel4vmmplatsupport: Rename PAGE_SIZE constant
